//id
//        executorName
//        visitPlace
//        visitScenePhoto
//        doctorSign
//        peopleSign
//        idType
//        idNo
//        residentInfoCode16
//        areaCode
//        visitUnitId
//        collectMode
//        inputDoctorId
//        unitName
//        exectorUUID
//        visitDate
//        checkMonth
//        weightValue
//        heightValue
//        complexion
//        anterior
//        anteriorFontanelBefore
//        anteriorFontanelAfter
//        eye
//        ear
//        hear
//        chest
//        abdominal
//        limb
//        teeth
//        teethDecay
//        activities
//        vitamin
//        assessment
//        twoItlState
//        twoItlPneumoniaNum
//        twoItlDiarrheaNum
//        twoItlTraumaNum
//        twoItlOther
//        referral
//        referralOther
//        referralMedicalId
//        referralDepartment
//        visitGuidance
//        visitGuidanceOther
//        skin
//        skinValue
//        eyeValue
//        chestValue
//        abdominalValue
//        limbValue
//        gait
//        gaitValue
//        complexionOther